name: Auto Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      # credentials are needed to push the tag
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 # zizmor: ignore[artipacked]
        with:
          fetch-depth: 0
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # delete local tag
          git tag -d v1 || true
          # Delete remote tag
          git push origin :refs/tags/v1 || true
          git tag v1
          git push --tags
